### ISSUE TITLE
Description could be a little more clear

### ISSUE THREAD

**Issue by dryabtse** [josefahmad/mongo-shardkey-tools#3]
Nice job Joseph!

One comment - I find the description to be rather ambiguous. For instance does the tool measure the number of spits that happened in a certain _range_ or does it capture the number of _chunks_ that get produced as a result of a chunk split?

If it's the former, then there is a semantical problem as a given chunk can only be split once - after that we're be dealing with N resulting chunks covering the range of the original chunk. Each of those resulting chunks can in return be split only once.

Subsequently, the X access should represent _ranges_ in which splits occurred, not _chunks_.

Please LMK if it makes sense to you.

**Comment by josefahmad** [comment]
Thanks Dmitry.

The tool plots the number of splits that happened in a certain range. More specifically a range corresponds to an _ancestor_ chunk, that is a chunk as it was at the earliest time in the changelog.

I agree that referring to these ranges as chunks is misleading. Will address this.

**Comment by josefahmad** [comment]
I pushed the changes to master, marking this as complete.

Thank you Dmitry for the input, feel free to reopen this issue if you believe it's not resolved.
